### ISSUE TITLE
create a tutorial that is compatible with https://github.com/redhat-scholars

### ISSUE THREAD

**Issue by goern** [AICoE/elyra-aidevsecops-tutorial#121]
SSIA ;)

**Comment by pacospace** [comment]
What do you mean compatible? Is there a reference document on how to create compatible tutorial for redhat-scholars? @goern

**Comment by goern** [comment]
all their tutorials are based on https://github.com/redhat-scholars/courseware-template maybe it is something we can adopt and reuse for op1st? @durandom

**Comment by durandom** [comment]
absolutely. https://github.com/operate-first/support/issues/113 <-- the workshop in there is also based on this framework.
Let's investigate how to turn it into a nice self-hosted page

**Comment by isabelizimm** [comment]
In the past, the FDE used https://github.com/sophwats/reproducible-workshops as a reproducible workshops template (can see an implementation [here](https://github.com/willb/openshift-ml-workflows-workshop). There is definitely room to update it and add some CI/CD elements to customize for op1st :)

**Comment by durandom** [comment]
I'd like to see something that looks good, is maintained and used by a larger community.

@blues-man @rcarrata @acidonper is the redhat-scholars template something used widely at RH consulting / SA?

**Comment by blues-man** [comment]
Well the goal is to create content usable by an "extended developer advocacy" teams in Red Hat from all departments :) It is used by both DAs and and SSAs at the moment, waiting for more contributions!

**Comment by acidonper** [comment]
@durandom, we are using this template but it is not a standard or used widely. 

I think that it will probably be used intensively in the future but it is not a fact. From my side, I have 4 workshops published with this template and I pretend to continue to use it...

- https://github.com/acidonper/redhat-workshop-cicd-gitops
- https://github.com/acidonper/redhat-workshop-hybrid-cloud
- https://github.com/acidonper/rh-service-mesh-v2-troubleshooting
- https://github.com/acidonper/rh-service-mesh-v2-istio-crtlplane

**Comment by goern** [comment]
@mayaCostantini havent you worked on this?

**Comment by mayaCostantini** [comment]
> @mayaCostantini havent you worked on this?

Yes indeed, see the [Managing Vulnerabilities with Thoth Tutorial](https://redhat-scholars.github.io/managing-vulnerabilities-with-thoth/managing-vulnerabilities-with-thoth/index.html) and the corresponding [repository](https://github.com/redhat-scholars/managing-vulnerabilities-with-thoth)

**Comment by mayaCostantini** [comment]
/close
See comment above

**Comment by mayaCostantini** [comment]
/remove lifecycle-rotten
/close
See comment above
