### ISSUE TITLE
add a Kubeflow-Serving part

### ISSUE THREAD

**Issue by goern** [AICoE/elyra-aidevsecops-tutorial#122]
**Is your feature request related to a problem? Please describe.**
As a Data Scientist, I trained my model and persisted it to the git repo, so that a deployment pipeline can pick it up and deploy it.

**Describe the solution you'd like**
KFServing to take model to deployment

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/kind feature
/sig pipelines

**Comment by pacospace** [comment]
cc @moficodes

**Comment by pacospace** [comment]
Depends-On: https://github.com/operate-first/support/issues/174

**Comment by goern** [comment]
/remove-lifecycle stale

is this still active?

**Comment by pacospace** [comment]
> /remove-lifecycle stale
> 
> is this still active?

We don't have kfserving in Operate First yet.
