### ISSUE TITLE
serve model as a function

### ISSUE THREAD

**Issue by goern** [AICoE/elyra-aidevsecops-tutorial#124]
**Is your feature request related to a problem? Please describe.**
As a Data Scientist,
I want to OpenShift Serverless/FaaS
as that it can serve my model

**Describe the solution you'd like**
tbd

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/kind feature

**Comment by pacospace** [comment]
Depends-On: https://github.com/operate-first/support/issues/84

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/thoth-application/issues/1069
