### ISSUE TITLE
Update tutorial to consider secure Elyra pipeline (credentials not exposed)

### ISSUE THREAD

**Issue by pacospace** [AICoE/elyra-aidevsecops-tutorial#136]
**Is your feature request related to a problem? Please describe.**
As Operate First user,

I want to see in the tutorial how I can set credentials before submitting my pipeline.

**Describe the solution you'd like**
See: https://github.com/operate-first/support/issues/155#issuecomment-824303561

**Describe alternatives you've considered**
Leave as it is.

**Additional context**

**Comment by harshad16** [comment]
This issue is just a tracker for https://github.com/operate-first/support/issues/155
