### ISSUE TITLE
Update serving portion of demo to use Seldon

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/elyra-aidevsecops-tutorial#176]
https://github.com/AICoE/meteor/issues/12 

Currently the tutorial uses a custom flask app to deploy the trained model. We should update this to use Seldon and deploy it on the moc zero cluster.

**Acceptance Criteria**

- [ ] Tutorial model is served using Seldon

**Comment by goern** [comment]
Please extend the tutorial in such a way, that we add deployment methods rather than replacing them. looking at MLOps aspects, it would be good to have a metric comparison based on different deployment methods.
