### ISSUE TITLE
Elyra tutorial training notebook fails in automation

### ISSUE THREAD

**Issue by oindrillac** [AICoE/elyra-aidevsecops-tutorial#185]
**Describe the bug**
The elyra demo training notebook does not execute successfully when run in automation.

**To Reproduce**
1. Uncomment `USE_CEPH` sections in `training.ipynb`.
2. Set environment variables with bucket credentials in .env and verify that the notebook runs successfully locally in JH whenn configured to `USE_CEPH`.
3. Set up an elyra pipeline, and submit a kubeflow pipeline run.
4. `training.ipynb` notebook fails with error `FileNotFoundError: [Errno 2] No such file or directory: '/opt/app-root/src/data/raw/ydata.pkl.aeC2B1C7'` 

**Expected behavior**
The training notebook should run the same way in automation as in JH environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/32435206/124927581-cb2d5400-dfcc-11eb-9ec0-f4c5e7bc0923.png)
![image](https://user-images.githubusercontent.com/32435206/124927620-d5e7e900-dfcc-11eb-8885-4c72afdb6553.png)

**Additional context**
Run logs: http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/pipeline/#/runs/details/15008a56-69eb-4069-a3c8-1fbba35c6b08

@pacospace any clue what might be going on here?

**Comment by pacospace** [comment]
Let's try with different path as discussed in call :) Let me know if it works @oindrillac! and thanks!!

**Comment by oindrillac** [comment]
@pacospace I played around with the path a little bit was able to find the fix. 

Here's what's going on:

The `training.ipynb`, we are looking to store the raw data at the `data/raw` folder from the root of the repo`raw_dataset_path = /opt/app-root/src/elyra-aidevsecops-tutorial/data/raw`. 

The notebook running in pipeline will not have access to the whole repo, so it cannot access the `..src/data/raw/` folder and throws a "No such file or directory" error.

To circumvent this, we can set the `raw_dataset_path` in the notebook to `data/raw`and set the dependencies of the training notebook to the raw files. This way, the training notebook can access those locations.   
"dependencies": [
              "data/raw/ydata.pkl",
              "data/raw/xdata.pkl",
              "data/raw/xtestdata.pkl",
              "data/raw/ytestdata.pkl" 
]

A PR is forthcoming. 🙂

**Comment by pacospace** [comment]
> @pacospace I played around with the path a little bit was able to find the fix.
> 
> Here's what's going on:
> 
> The `training.ipynb`, we are looking to store the raw data at the `data/raw` folder from the root of the repo`raw_dataset_path = /opt/app-root/src/elyra-aidevsecops-tutorial/data/raw`.
> 
> The notebook running in pipeline will not have access to the whole repo, so it cannot access the `..src/data/raw/` folder and throws a "No such file or directory" error.
> 
> To circumvent this, we can create a `data/raw` dir within the notebooks dir and add the raw files to it locally. We can set the `raw_dataset_path` in the notebook to `data/raw` and set the dependencies of the training notebook to the raw files. This way, the training notebook can access those locations.
> "dependencies": [
> "data/raw/ydata.pkl",
> "data/raw/xdata.pkl",
> "data/raw/xtestdata.pkl",
> "data/raw/ytestdata.pkl"
> ]
> 
> A PR is forthcoming.

What about the structure we got from cookiecutter and aiops template? in that way we are not using that, correct? So to my understanding from your explanation, we cannot access other dependencies of the notebook in a path that is not at the same root of the notebook? Is it just a problem when we run in a kfp pipeline? In that case I would open an issue in Elyra upstream to ask if that behaviour is expected. wdyt?

**Comment by oindrillac** [comment]
> Is it just a problem when we run in a kfp pipeline? In that case I would open an issue in Elyra upstream to ask if that behaviour is expected. wdyt?

@pacospace I think this is an [expected behavior](https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html) by Elyra. @Shreyanand had opened an [issue](https://github.com/elyra-ai/elyra/issues/1734) for this and although it may not be the most elegant solution, we might be able to [use symlinks to circumvent this](https://github.com/elyra-ai/elyra/issues/1706#issuecomment-849729602). 

Either way, unless we specify explicit file dependencies in the training notebook, it is expected to fail.

**Comment by pacospace** [comment]
> > Is it just a problem when we run in a kfp pipeline? In that case I would open an issue in Elyra upstream to ask if that behaviour is expected. wdyt?
> 
> @pacospace I think this is an [expected behavior](https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html) by Elyra. @Shreyanand had opened an [issue](https://github.com/elyra-ai/elyra/issues/1734) for this and although it may not be the most elegant solution, we might be able to [use symlinks to circumvent this](https://github.com/elyra-ai/elyra/issues/1706#issuecomment-849729602).
> 
> Either way, unless we specify explicit file dependencies in the training notebook, it is expected to fail.

Thanks @oindrillac, then we need elyra >= 2.3 in ODH, but from Elyra I see they are working on 3.0 already. I asked upstream in the same issue, what is their milestone and ETA so we can get it in ODH and Operate First.

**Comment by oindrillac** [comment]
thanks @pacospace
