### ISSUE TITLE
Rebuild Jupyterbook files to reflect changes made in #186

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/elyra-aidevsecops-tutorial#188]
#186 added relative links to some of the content pages. In order for those changes to be reflected in the [published book](https://aicoe.github.io/elyra-aidevsecops-tutorial/README.html) we need to rebuild the book and update the files in `docs/` in our repo. 

Please follow the instructions [here](https://docs.google.com/document/d/1fkLko3tG4Na_3UbGA-YzTqU-H42r-cU-skX07luyXho/edit) to include the updated html files. (if these instructions are confusing or insufficient for this task please leave a comment and we can update them).

**Comment by MichaelClifford** [comment]
related to https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/189

**Comment by pacospace** [comment]
@MichaelClifford do we still need this issues, based on https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/268?

**Comment by MichaelClifford** [comment]
No : )
