### ISSUE TITLE
Move site content to gh-pages branch

### ISSUE THREAD

**Issue by oindrillac** [AICoE/elyra-aidevsecops-tutorial#189]
We wish to move the site html content to a separate `gh-pages` branch such that we will not have a large `docs` folder and strange hierarchies like `docs/docs` and we can avoid the manual moving of content from `_build` to `docs` folder each time we wish to build the site. This way, we can avoid outdated site content being stored in the same repo if we fail to re-build the site content with each content modification PR.

Can @pacospace or any admin/maintainer of this repo help create a `gh-pages` branch so that PRs can be sent to it?

**Comment by pacospace** [comment]
@oindrillac @MichaelClifford is this still required based on https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/268?

**Comment by MichaelClifford** [comment]
This issue is no longer needed due to #268 
/close
