### ISSUE TITLE
Publicly accessible namespace and bucket for pre-requisite.md [meteor]

### ISSUE THREAD

**Issue by oindrillac** [AICoE/elyra-aidevsecops-tutorial#216]
Currently in [pre-requisite.md](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/pre-requisite.md) we ask users to 
- Request access to a namespace
- Request access to a bucket

In both cases can we just have one that is publicly accessible instead to avoid breaking the flow of the tutorial?
This would be a special case, independent of meteor functionality.

Acceptance Criteria:
- [ ] Create new or use existing public namespace for users to make use of during the tutorial.
- [ ] Create new or use existing public bucket for users to make use of during the tutorial.

**Comment by oindrillac** [comment]
Do we have a public namespace which the users can share and experiment with independent of Meteor?
As for acceptance criteria 2 can we use opf-datacatalog?

cc @MichaelClifford @4n4nd

**Comment by 4n4nd** [comment]
> Do we have a public namespace which the users can share and experiment

I don't think we have a public namespace available for users
@HumairAK @tumido

**Comment by MichaelClifford** [comment]
@oindrillac yes, I think we should use opf-datacatalog for public storage. But we do need to decide if we should create a public namespace or not.

**Comment by MichaelClifford** [comment]
@tumido Any thoughts on how we should handle providing a namespace for those who would deploy this tutorial through Meteor?

**Comment by tumido** [comment]
Hm, I wonder.. can we make this all happen in the JupyterHub namespace? That way we can try using jupyter hub single user profiles to provision a bucket for us.

@anishasthana @vpavlin can we do that? Can we make Jupyter Hub to submit a resource manifest on the user behalf and take care of the resources lifecycle? We would like to create ObjectBucketClaim together with spawning of a JypyterHub image.

**Comment by MichaelClifford** [comment]
@tumido there is also the issue of deploying the [inference endpoint](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/model-deployment/flask-application.md#2-deploy-your-application). That currently can be done either by opening an issue and waiting for someone to deploy the app through ArgoCD, or using the `oc` commands directly. If we are trying to avoid waiting on humans to address issues, could the deployment be done directly through JupyterHub as well with `oc`? or could the ArgoCD issue process be automated somehow?

**Comment by tumido** [comment]
Hm.. we plan on enabling automated deployment through Argocd, without human intervention (auto approve on CI pass) Would that solve it?

https://github.com/operate-first/workshop-apps/pull/33

**Comment by goern** [comment]
any progress on this? is it still active?

/priority backlog
/kind feature

**Comment by MichaelClifford** [comment]
I think the namespace issue has been addressed via use of argoCD. 

However, is there a public bucket we want to use for the demo moving forward? Or do we still want users to request one? If we want to use a public bucket, I think it needs to be created on smaug and docs for interacting with it need to be added to this repo. 

@pacospace @tumido  WDYT?

**Comment by pacospace** [comment]
> I think the namespace issue has been addressed via use of argoCD.
> 
> However, is there a public bucket we want to use for the demo moving forward? Or do we still want users to request one? If we want to use a public bucket, I think it needs to be created on smaug and docs for interacting with it need to be added to this repo.
> 
> @pacospace @tumido WDYT?

I think if there is a public one would be definetly better and easier, but on the other side it might require a big bucket, I don't know about memory resources.

**Comment by goern** [comment]
what is the status of this one?

**Comment by HumairAK** [comment]
There's a public bucket here: https://www.operate-first.cloud/apps/content/odh/trino/access_public_bucket.html 
not sure if it's big enough
