### ISSUE TITLE
Modify explore-notebooks-and-manage-dependencies.md to make it specific to tutorial [meteor]

### ISSUE THREAD

**Issue by oindrillac** [AICoE/elyra-aidevsecops-tutorial#218]
In the [Explore-notebook](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/explore-notebooks-and-manage-dependencies.md) document
users are asked to leave the project to learn about a tool. There should be instructions for this tutorial specific for dependency and overlays use. The instructions are not clear about how to run the notebooks. 

Acceptance Criteria:
- [ ] Make dependency management instructions specific to tutorial
- [ ] Add instructions on how to run notebooks eg: any env variables that need to be configured

**Comment by pacospace** [comment]
> In the [Explore-notebook](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/explore-notebooks-and-manage-dependencies.md) document
> users are asked to leave the project to learn about a tool. There should be instructions for this tutorial specific for dependency and overlays use. The instructions are not clear about how to run the notebooks.
> 
> Acceptance Criteria:
> 
> * [ ]  Make dependency management instructions specific to tutorial
> * [ ]  Add instructions on how to run notebooks eg: any env variables that need to be configured

The new release v0.10.0 of jupyterlab-requirements will have jupyter magic commands: `%horus`, no need to use UI anymore, everything will be possible from cells: https://github.com/thoth-station/jupyterlab-requirements#horus-magic-command, wdyt? I will create a demo of v0.10.0 after the release. We already introduced a CLI for automatic creation of kernels from notebook dependencies for Meteor: https://www.youtube.com/watch?v=fW0YKugL26g (https://github.com/AICoE/meteor/issues/35)

**Comment by oindrillac** [comment]
that is great @pacospace! we should definitely modify the tutorial to use `horus`. Is this already available on operate first JupyterHub? I'm unable to test it on JH due to the ongoing networking issues.

**Comment by pacospace** [comment]
> that is great @pacospace! we should definitely modify the tutorial to use `horus`. Is this already available on operate first JupyterHub? I'm unable to test it on JH due to the ongoing networking issues.

We will make it available soon!

**Comment by pacospace** [comment]
Magic commands released :D and recoridng available: https://www.youtube.com/watch?v=FjVxNTXO70I&t=149s

**Comment by pacospace** [comment]
new image is available in JH on Operate First.

**Comment by pacospace** [comment]
Depends-On: https://github.com/thoth-station/jupyterlab-requirements/issues/385

**Comment by oindrillac** [comment]
Thanks @pacospace! So  it seems like currently, the availability of horus magic commands on jupyterhub is blocked by this https://github.com/msm1089/ipynbname/issues/8? 
In the mean time, shall we update the instructions to use the horus command line to manage dependencies?

**Comment by pacospace** [comment]
> Thanks @pacospace! So it seems like currently, the availability of horus magic commands on jupyterhub is blocked by this [msm1089/ipynbname#8](https://github.com/msm1089/ipynbname/issues/8)?
> In the mean time, shall we update the instructions to use the horus command line to manage dependencies?

We could but give some some days to find a solution first that works on jupyterhub, not sure when that package will be updated to be honest :/

**Comment by pacospace** [comment]
available in https://quay.io/repository/thoth-station/s2i-elyra-custom-notebook?tab=tags v0.3.3. Tested with Meteor.

![Screenshot from 2021-09-02 10-04-25](https://user-images.githubusercontent.com/27498679/131837277-b528dbf8-e9f6-497a-a4be-f4775411b891.png)

**Comment by pacospace** [comment]
@oindrillac what do we miss for this issue?

**Comment by oindrillac** [comment]
thanks @pacospace. we can close this issue
