### ISSUE TITLE
explore-notebooks-and-manage-dependencies.md should provide instructions on how to run the provided notebooks [meteor]

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/elyra-aidevsecops-tutorial#224]
`explore-notebooks-and-manage-dependencies.md` should provide instructions for how to access the notebooks in JL and how to run them so that users can set their own dependencies and kernels and train their own models.

Acceptance Criteria:

- [x] additional images and details added to this *.md so that users know how to access and run notebooks on JL

**Comment by oindrillac** [comment]
currently depends on https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/218#issuecomment-899343216

**Comment by goern** [comment]
is this still active?

/kind feature
/priority backlog
