### ISSUE TITLE
Add meteor info to `prerequsit.md` [meteor]

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/elyra-aidevsecops-tutorial#225]
The pre-reqs for this tutorial are different depending on whether a user wants to set up everything themselves or use meteor. This doc should be updated to reflect what meteor will provide you if you use it and what users will still need to prepare for themselves.

With meteor the following will be provided for you:
* OpenShift environment/Jupyter hub  

The following will still need to be set up independent of meteor:
* Github account + token
* Namespace for deployment
* Cloud object storage
* Kubeflow pipeline.

**Comment by MichaelClifford** [comment]
cc @pacospace @tumido Is the list of "automated by meteor" vs "independent of meteor" correct as far as using it for devconf?

**Comment by tumido** [comment]
I think yes, the list seems correct to me. We may try automating the namespace and cloud storage via Meteor, but not for devconf, I don't have enough time to make that happen probably.
