### ISSUE TITLE
Include meteor specific instructions to `setup-initial-environment.md` [meteor]

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/elyra-aidevsecops-tutorial#226]
Instructions 2 and 3 in `setup-initial-environment.md` don't make sense if you're using meteor. We should add additional instructions that note you can skip those steps if using meteor. 

Acceptance Criteria: 

- [ ] Add additional instructions if using meteor to `setup-initial-environment.md`.

**Comment by chauhankaranraj** [comment]
Is this a possible duplicate of #217 or does it have a different purpose?

**Comment by oindrillac** [comment]
It seems to me like they only have different acceptance criteria. If we are keeping #217, we should modify the acceptance criteria in #217 to not remove any content, rather modify the instructions to account for both the scenarios based on our discussions,

**Comment by MichaelClifford** [comment]
closing, duplicate
