### ISSUE TITLE
`build-images.md` should include details on how to setup AICoE CI and Thoth on a fork [meteor]

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/elyra-aidevsecops-tutorial#227]
`build-images.md` has instructions that are dependent on the user setting up their fork to use AICoE CI and Thoth tooling, but [redirects](https://github.com/AICoE/aicoe-ci#setting-aicoe-ci-on-github-organizationrepository) the user out of the tutorial learn how to do that. I suggest that we add the instructions directly into this document to avoid breaking the flow of the tutorial.

Acceptance Criteria:

- [ ]  add [instructions](https://github.com/AICoE/aicoe-ci#setting-aicoe-ci-on-github-organizationrepository) to add AICOE-CI GitHub application  
- [ ]  add [instructions](https://github.com/AICoE/aicoe-ci#setting-aicoe-ci-on-github-organizationrepository) to send invite to Seshesta
- [ ]  explain the required aicoe-ci config file is already present from the template. 

All these instructions can be adapted from [here](https://github.com/AICoE/aicoe-ci#setting-aicoe-ci-on-github-organizationrepository)

**Comment by isabelizimm** [comment]
\assign @isabelizimm
