### ISSUE TITLE
Explain kfp runtime & runtime images in `create-ai-pipeline.md` [meteor]

### ISSUE THREAD

**Issue by oindrillac** [AICoE/elyra-aidevsecops-tutorial#231]
Data Scientists interested in cloud native development may not be familiar with runtime images and kubeflow pipeline runtimes before starting this tutorial.

It might be worth adding some descriptions about what each does, to make these concepts clear to the data science user.

Acceptance Criteria:
- [ ] Add a one line explanation for the purpose of a runtime image and a kubeflow pipeline runtime.

**Comment by MichaelClifford** [comment]
maybe something as simple as "In order to get your elyra pipeline to work correctly we need 2 things; the names of your notebook images added to the pipeline metadata so it knows were to find them, and a defined runtime so that kubeflow knows how to run the whole pipeline"
