### ISSUE TITLE
Conclusion or Summary doc [meteor]

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/elyra-aidevsecops-tutorial#241]
The tutorial should include a summary/conclusion/congratulations page that comes after `monitor-model.md` letting the user know they've completed all the steps in the tutorial and re-iterate what they've accomplished with all of the AICoE tool support.

**Comment by isabelizimm** [comment]
\assign @isabelizimm

**Comment by isabelizimm** [comment]
@pacospace do you know why Sesheta will not listen to me? :sweat_smile:

**Comment by MichaelClifford** [comment]
> do you know why Sesheta will not listen to me?

cc @harshad16

**Comment by pacospace** [comment]
> @pacospace do you know why Sesheta will not listen to me? 😅

Weird, @goern can you please check if Isabel has write privilegies here?
