### ISSUE TITLE
build-image docs does not specify if I need to create a quay repo

### ISSUE THREAD

**Issue by suppathak** [AICoE/elyra-aidevsecops-tutorial#253]
The [build-image.md](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/build-images.md) doc in the tutorial does not specify whether the user need to create a quay repo called elyra-aidevsecops-tutorial. Would this be created automatically by the robot account setup in the previous step? or, Is the doc missing a step/instruction to create a repo?

**Comment by pacospace** [comment]
Solved, you can check here: https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/thoth-aicoe-services.md#create-a-first-release-and-image-of-your-project
