### ISSUE TITLE
Remove "my binder" from launch button 

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/elyra-aidevsecops-tutorial#264]
The [_config.yml](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/_config.yml) should remove the binderhub url so that users will link to Jupyter hub.

**Comment by goern** [comment]
any movement on this? still active and required?

**Comment by MichaelClifford** [comment]
@isabelizimm was this issues addressed in other repos?

**Comment by isabelizimm** [comment]
It was addressed, but it looks like the suggested fix does not work. Opened an [issue upstream ](https://github.com/executablebooks/jupyter-book/issues/1486)

**Comment by goern** [comment]
cool, let's close this and keep an eye on the upstream issue. 

/close
