### ISSUE TITLE
Remove section on adding Sesheta as collaborator for AICOE CI

### ISSUE THREAD

**Issue by pacospace** [AICoE/elyra-aidevsecops-tutorial#289]
**Is your feature request related to a problem? Please describe.**
Depends-On: https://github.com/AICoE/aicoe-ci/issues/136

**Describe the solution you'd like**
Remove section on adding Sesheta as collaborator for AICOE CI

**Describe alternatives you've considered**

**Additional context**

**Comment by codificat** [comment]
/lifecycle frozen
while waiting for https://github.com/AICoE/aicoe-ci/issues/136

**Comment by goern** [comment]
is this still required?

**Comment by codificat** [comment]
> is this still required?

I think so, yes - once the option exists (no dependency on a sesheta invite), then it's necessary to update the tutorial. So, still pending on https://github.com/AICoE/aicoe-ci/issues/136

**Comment by goern** [comment]
ping
