### ISSUE TITLE
use tekton chains to build the tutorial

### ISSUE THREAD

**Issue by goern** [AICoE/elyra-aidevsecops-tutorial#461]
**Is your feature request related to a problem? Please describe.**
We want to use Tekton Chains during the build of this tutorial. It might be that we need to extend the Tekton pipelines used by meteor...

**Describe the solution you'd like**
- [ ] refactor meteor tekton artifacts to https://github.com/thoth-station/helm-charts/tree/main/charts/meteor-pipelines
- [ ] let have the meteor deployment use the helm chart
- [ ] extend using chains
- [ ] figure out how the signed artifacts can be used on op1st/odh

**Describe alternatives you've considered**
TBD

**Additional context**
this is supporting OCTO Summit Demo

/kind feature
/priority important-soon
/assign @harshad16 
/assign @pacospace

**Comment by goern** [comment]
seeAlso https://github.com/operate-first/support/issues/438

**Comment by harshad16** [comment]
The requirement for tekton chains to work with pipelines is added to the pipelines.
we are just waiting on quay to get updated to a version that is compatible with the image verification 
This is being tracked here: https://github.com/AICoE/aicoe-ci/issues/150 and https://github.com/AICoE/summit-2021-octo-keynote/issues/7

Thanks for the issue.
