### ISSUE TITLE
Unable to add runtime images to Elyra metadata

### ISSUE THREAD

**Issue by theckang** [AICoE/elyra-aidevsecops-tutorial#484]
**Describe the bug**
While running the tutorial, I am unable to add runtime images to Elyra metadata using the UI or the CLI.

**To Reproduce**
Steps to reproduce the behavior for UI:
1. Open Operate First JupyterHub notebook with "AICoE Elyra AIDevSecOps Tutorial Notebook Image"
2. Navigate to Runtime Image
3. UI throws error (see attached screenshot below)

Steps to reproduce the behavior for CLI:
1. Open Operate First JupyterHub notebook with "AICoE Elyra AIDevSecOps Tutorial Notebook Image"
2. Open a Terminal
3. Use CLI to add runtime

```
$ elyra-metadata install runtime-images --display_name="Tutorial Training Step" --description="Training Step Tutorial" --image_name="quay.io/thoth-station/elyra-aidevsecops-training:v0.10.0"
Traceback (most recent call last):
  File "/opt/app-root/bin/elyra-metadata", line 5, in <module>
    from elyra.metadata.metadata_app import MetadataApp
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/__init__.py", line 23, in <module>
    from .pipeline import PipelineExportHandler, PipelineSchedulerHandler, PipelineProcessorManager
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/pipeline/__init__.py", line 22, in <module>
    from .processor_kfp import KfpPipelineProcessor
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/pipeline/processor_kfp.py", line 24, in <module>
    from black import format_str, FileMode
  File "/opt/app-root/lib64/python3.8/site-packages/black/__init__.py", line 48, in <module>
    from black.files import find_project_root, find_pyproject_toml, parse_pyproject_toml
  File "/opt/app-root/lib64/python3.8/site-packages/black/files.py", line 26, in <module>
    from black.handle_ipynb_magics import jupyter_dependencies_are_installed
  File "/opt/app-root/lib64/python3.8/site-packages/black/handle_ipynb_magics.py", line 15, in <module>
    from typing_extensions import TypeGuard
ImportError: cannot import name 'TypeGuard' from 'typing_extensions' (/opt/app-root/lib64/python3.8/site-packages/typing_extensions.py)
```

**Expected behavior**
The UI or CLI provides the ability to load a runtime image to Elyra metadata.

**Screenshots**
![Screen Shot 2022-01-12 at 2 22 55 PM](https://user-images.githubusercontent.com/10468378/149416335-d48f28e4-88ab-463f-857b-5a68551a1eba.png)

**Comment by pacospace** [comment]
@theckang thanks for opening this issue!!
I debug a bit this image and it seems like some updates in the underlying layers broke elyra. I will investigate more and come make sure we fix this, if you want to continue the tutorial you can use the `Experimental Elyra Notebook Image` that does not show this problem.

**Comment by harshad16** [comment]
After brainstorming with @pacospace  over this issue, we have found the exact reason for the issue.
we have to update the dependencies in the project. 
we will be doing that shortly, till then if required use the alternative solution suggested in the above comment.

**Comment by harshad16** [comment]
All the images are updated with the fix.

Tested on the latest experiment image: 
```
$ elyra-metadata install runtime-images --display_name="Tutorial Training Step" --description="Training Step Tutorial" --image_name="quay.io/thoth-station/elyra-aidevsecops-training:v0.10.0"

Metadata instance 'tutorial_training_step' for schema 'runtime-image' has been written to: /opt/app-root/src/.local/share/jupyter/metadata/runtime-images/tutorial_training_step.json
```
please check on your side and close the issue if feel statisfied.

**Comment by theckang** [comment]
Thank you!
