### ISSUE TITLE
[3pt] Provide documentation for Thoth configuration

### ISSUE THREAD

**Issue by negillett** [AICoE/elyra-aidevsecops-tutorial#501]
**Is your feature request related to a problem? Please describe.**
When reading through thoth-aicoe-services.md it's unclear how to configure thoth beyond setting `maintainers` under `managers` and there's no (direct) link to any thoth documentation.

E.g., Nothing currently tells me what `runtime_environments` is for or what options it supports.

**Describe the solution you'd like**
I seems necessary to have configuration (.thoth.yaml) options detailed somewhere.

**Describe alternatives you've considered**
Perhaps sufficiently detailed documentation already exists for thoth. I've so far been unable to find anything but in such a case, point users there for more information.

**Additional context**
The tutorial page directed me to https://github.com/AICoE/aicoe-ci#setting-aicoe-ci-on-github-organizationrepository which had no info on thoth but directed me to https://github.com/AICoE/aicoe-ci/blob/master/docs/thoth-bots-setup.md which directed me to https://thoth-station.ninja/docs/developers/kebechet/managers/thoth_advise.html#configuration which deadends at https://github.com/thoth-station/thamos. The last page has _some_ information on configuration but is incomplete. It's clear that our example, `runtime_environments`, is used in building images but when and how the images are used is unclear.

**Comment by harshad16** [comment]
Suggestions(for assignee):
- [ ] Include the default template in docs: https://github.com/thoth-station/thamos/blob/master/thamos/data/defaultThoth.yaml
- [ ] Showcase the runtime environments on the help site.
API of the solver endpoint to get the list of support.
- [ ] [spike]check what is missing from user's perspective https://github.com/thoth-station/thamos#support-for-multiple-runtime-environments
- [ ] document the different runtime available with example and description

/triage accepted
/priority backlog
