### ISSUE TITLE
Docs don't explain how to select Python version

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [AICoE/elyra-aidevsecops-tutorial#531]
**Describe the bug**
It is totally opaque to me, as a JupyterHub user, how to select the same python version for the runtime image that matches the python version of my notebook.

**To Reproduce**
1. Go to Command Pallete (Cmd + Shift + C)
2. Click on Manage Runtimes
3. Notice that available runtime `Anaconda (2021.11) with Python 3.x
[continuumio/anaconda3:2021.11](https://hub.docker.com/r/continuumio/anaconda3)` does not describe a python version
4. Neither does `Pandas 1.4.1
[amancevice/pandas:1.4.1](https://hub.docker.com/r/amancevice/pandas)`

**Expected behavior**
I expect the documentation to explain how the version of Python is selected (and potentially how I as the user might select it).

**Screenshots**

**Additional context**

**Comment by codificat** [comment]
Many thanks for your feedback.

I think there is some misunderstanding around the workflow / purpose of this tutorial, or I might be missing some additional context here - something worth clarifying in any case.

Let me try to find out the details:

> how to select the same python version for the runtime image that matches the python version of my notebook.

In theory, I believe you should not have to worry about that to begin with. At least not from within the jupyterlab interface to manage runtime images.

The tutorial aims to present a workflow that includes automated build and maintenance of container images tailored to your project's needs (including notebooks). The process to do that is documented in the [Create a first release and image](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/0ff073756d4b6b1f7b787cb01ce42b7c3c7859c8/docs/source/thoth-aicoe-services.md) step.

As the document mentions, for the purpose of this tutorial, this process has been already prepared for this tutorial's repository, and container images that match the requirements from the notebooks in this tutorial are already (automatically) built and maintained.

In other words: by using the images that are generated for the repo, your notebook should already be using a runtime that matches its requirements.

These requirements are specified outside of the elyra environment itself.

> * Click on Manage Runtimes
> 
> * Notice that available runtime `Anaconda (2021.11) with Python 3.x [continuumio/anaconda3:2021.11](https://hub.docker.com/r/continuumio/anaconda3)` does not describe a python version

The list of images presented there are outside of the scope of this tutorial.

In the context of the tutorial, you would only need to manage elyra image runtimes when you want to use the image(s) that are custom-built for your project as part of a pipeline. You would only go to manage runtimes to add your images.

This is documented e.g. in the [Create AI Pipeline](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/0ff073756d4b6b1f7b787cb01ce42b7c3c7859c8/docs/source/create-ai-pipeline.md) step.

I hope this explains the "mismatch" I am seeing in the request here - again, something we would like to clarify more in the tutorial.

If all this was already clear, then please help me better understand your goal. Some concrete details might help: if you are following the tutorial but using a different repo / set of notebooks, can you share what these are? Do you have / plan to have custom container images for your project / notebooks?  What is missing from the ones provided from this tutorial?

Thanks

**Comment by MichaelTiemannOSC** [comment]
Thanks for that explanation.  I've created an issue on the OS-Climate side that recognizes the work that needs to be done to harmonize how we think about the problem with how the AICoE best practices work: https://github.com/os-climate/OS-Climate-Community-Hub/issues/54

To make it easier to "show my work", I'm going to try to integrate what these tutorials explain into the work I'm doing here https://github.com/os-climate/essd-ingest-pipeline/tree/iceberg-dbt

I already see that https://github.com/os-climate/essd-ingest-pipeline/blob/iceberg-dbt/notebooks/osc-essd-00-init.ipynb is an anti-pattern, because it is meaningless to have a notebook do a bunch of pip installs in a pipeline-oriented world.  I need to put those dependencies into `Pipfile` (and `Pipfile.lock`), but I also need to figure out how to get the Elyra nodes to actually install those libraries into the containers it creates.  I tried to do this yesterday with another repo that used the same anti-pattern and despite all the edits I did, I failed to accomplish that.

**Comment by MichaelTiemannOSC** [comment]
BTW, it took me about 3 hours to straighten out dependency conflicts intrinsic to dbt-core, dbt-trino, and the rest of the world to produce a Pipfile.lock that was consistent.  Now that I've done that, I really want to take advantage of either my Pipfile or Pipfile.lock as a reference point for how my Elyra runtime image gets built!

**Comment by goern** [comment]
@MichaelTiemannOSC that sounds to me like a) a use case for `thamos advise` and b) a use case for a custom notebook image build (ODH calls this feature  CNBi, we might have called it BYON before)

@mayaCostantini could you please have a look at the notebook repo Michael has created and make sure that we can advise on them and all their dependencies. 

@codificat or @Gregory-Pereira could you (for now manually) create a pipeline that will build/deliver custom notebook image to Michael's os-climate deployment of ODH @codificat and create issues from here in our repos?! ;) 1000thanks
