### ISSUE TITLE
show off how an Elyra pipeline is using CPU and GPU

### ISSUE THREAD

**Issue by goern** [AICoE/elyra-aidevsecops-tutorial#55]
**Is your feature request related to a problem? Please describe.**
As a Data Scientist,
I want to run an Elyra Pipeline,
so that some steps utilize CPU
and so that the training step utilized GPU

The pipeline might have 4 standard steps that end up in a trained model on the repo, so that it could be tagged and released...

The result should be a demo on Op1st.

**Describe the solution you'd like**
tbd

**Describe alternatives you've considered**
n/a

**Additional context**
the basic question is, how we could share that GPU in a Data Scientist team in an efficient way.

Cc: @cfchase 

/kind feature
/sig user-experience

**Comment by pacospace** [comment]
Elyra introduced new features when setting the steps of the pipelines:
![Screenshot from 2021-02-08 20-08-34](https://user-images.githubusercontent.com/27498679/107269215-90d58000-6a49-11eb-8ac1-f8fa0ede6f35.png)

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> As a Data Scientist,
> I want to run an Elyra Pipeline,
> so that some steps utilize CPU
> and so that the training step utilized GPU
> 
> The pipeline might have 4 standard steps that end up in a trained model on the repo, so that it could be tagged and released...
> 
> The result should be a demo on Op1st.
> 
> **Describe the solution you'd like**

- [ ] pre-requisite: Thoth need to discover GPU available on the cluster to provide recommendation on the use of GPU
- [ ] Once dependencies optimized for GPU are recommended, they are stored on overlays
- [ ] an image need to be create for step with GPU

> 
> **Describe alternatives you've considered**
> n/a
> 
> **Additional context**
> the basic question is, how we could share that GPU in a Data Scientist team in an efficient way.
> 
> Cc: @cfchase
> 
> /kind feature
> /sig user-experience

**Comment by codificat** [comment]
From today's refinement session: we believe the content is already there to show the metrics from the [gather-metrics task](https://github.com/AICoE/aicoe-ci/blob/master/tasks/gather-and-process-metrics.yaml#L84).

/close
